### ISSUE TITLE
Do not turn off widget highlighting

### ISSUE THREAD

**Issue by megafreeman** [VirtoCommerce/vc-module-catalog-publishing#11]
In our project, we have several detail evaluators that check various parameters in properties blade. If in one of them completeness less than 100% the Properties widget highlighted in this manner:
![image](https://user-images.githubusercontent.com/7536694/32842102-e683e15e-ca24-11e7-8ab4-5ed51e3ed28c.png)

But now we have result completeness collection, where two evaluators have 100%, and just one has 0% completeness:
![image](https://user-images.githubusercontent.com/7536694/32842297-65263d36-ca25-11e7-89bb-c7d66ca6f1bc.png)

In this case the widget is not highlighted:
![image](https://user-images.githubusercontent.com/7536694/32842541-039cb4b8-ca26-11e7-98e6-37b7d0665e63.png)

Need to change the logic of widget highlighting and disable turn off widget highlighting if there is at least one completeness below 100%.

**Comment by asvishnyakov** [comment]
For the same product, in details, only one Properties must appear. I think you're wrong extending module.
