### ISSUE TITLE
Wrong lables

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-module-catalog-publishing#14]
Wrong lables into "Channel evaluate progress" blade.
Catalog publishing module Version 1.1.1
Catalog module Version 2.21.7

![image](https://user-images.githubusercontent.com/7644848/38933783-4350fd72-431a-11e8-92b1-696b11e00761.png)

**Comment by tatarincev** [comment]
Released
https://github.com/VirtoCommerce/vc-module-catalog-publishing/releases/tag/v1.1.2
