### ISSUE TITLE
Create Integration Point for Enrichment form for Proffs project

### ISSUE THREAD

**Issue by sansey2k** [VirtoCommerce/vc-module-catalog-publishing#15]
This improvment includes also code review of current Channels module.
Dod : Updated Channels module supports Integration with different blades, not only with Physical Item Details.

**Comment by sansey2k** [comment]
@tatarincev Привет!
Делюсь новостями - Тигран @Tilesto  создал прототип формы с одной вкладкой Main и может ей поделиться, начиная с завтрашнего дня.
Предлагаю перейти к созданию Интеграционной точки на платформе. А форму Тиграна можно использовать для тестирования integration point.

С уважением,
Александр Зыкин

**Comment by tatarincev** [comment]
I've been added the special extension point which allows using a custom view for product enrichment process. 
Here is the example of code which you need to add on your module side in order to override the default product details view on your own.
```
angular.module('virtoCommerce.catalogPublishingModule')
    .factory('virtoCommerce.catalogPublishingModule.productCompletenessBladeFactory', function () {
        //Nothing to do here. Default factory implementation return null to use default product detail blade as primary view for product completeness
        //To override that factory in custom module just need to redefine it with same name and module
         return function (product) {
            return {
               id: "{{blade identifier}}",
               product: product,
               controller: '{{controller fqn }}',
               template: '{{path to template}}'
            };
        };
    });
```

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog-publishing/releases/tag/v1.1.3
